### ISSUE TITLE
Is there an ETA for when this plugin will be available in Obsidian's 'Community Plugins'?

### ISSUE THREAD

**Issue by MrNotch9** [nybbles/obsidian-pocket#26]
This is a promising extension and I can't wait for it to go public

**Comment by nybbles** [comment]
Thanks for your interest in the plugin!

It will be added to Obsidian's list of community plugins once this pull request goes in: https://github.com/obsidianmd/obsidian-releases/pull/346. However, I am waiting for Obsidian to release v0.12.11+ with the request API (see https://github.com/obsidianmd/obsidian-releases/pull/346#issuecomment-880391943), so that I can make necessary changes and then get the plugin added to the community plugins list (see https://github.com/nybbles/obsidian-pocket/issues/27 for the work needed).

It will take some time, as I need to wait for the Obsidian release with the required functionality to be released, and then make the necessary changes and push out a new version.

In the interim, you can also manually download and install the plugin (just like any other Obsidian plugin), if you already know how to do that. If you don't, I'd advise just waiting.

Thanks for your interest and patience!

**Comment by nybbles** [comment]
@MrNotch9, if you want to be notified when the plugin is available for install via Obsidian community plugin list, please watch https://github.com/nybbles/obsidian-pocket/issues/28. I'll close out this issue as the question has been answered.
