### ISSUE TITLE
Pocket items not opening in browser

### ISSUE THREAD

**Issue by oldjove** [nybbles/obsidian-pocket#32]
Hi, very excited about this app. Looks like it will be great for my workflow. However, at the moment when I CRTL+click on an item in the Pocket list, the appropriate note is created, but the webpage doesn't load in Firefox and I get this error message: "You'll need a new app to open this app."

Any idea what might be going wrong?

**Comment by oldjove** [comment]
Actually, this also happens when I normal click.

**Comment by thecookiemomma** [comment]
Me too. Neither clicking nor ctrl+clicking on the links works.  I believe for Windows, the link needs to be obsidian://name for the click and regular http:// for the ctrl+click.  I may be wrong, though.

**Comment by nybbles** [comment]
@oldjove and @thecookiemomma, thanks for the bug report. Are you both on Windows? and this happens for all Pocket entries?

**Comment by oldjove** [comment]
@nybbles Yep, I'm on Windows 10. It seems to happen for all entries. At least I haven't noticed any exceptions.

**Comment by nybbles** [comment]
Hello @oldjove and @thecookiemomma, the problem you encountered should be fixed now, if you upgrade to https://github.com/nybbles/obsidian-pocket/releases/tag/0.3.2 via the Obsidian app.

You might still not be able to create a note for a Pocket item if you specify invalid paths (under plugin settings) for Pocket item note template file location and Pocket item notes folder location, but you will see a clear error message. If you leave those settings blank, they will use defaults (i.e. a blank template, and notes for Pocket items found and stored in the root folder).

I also switched the Windows modifier key to open the URL to Alt, rather than Meta, because it seemed as though on Windows the Meta key just is globally bound to open the start menu. I'm not a Windows user, so I missed that.

Please LMK if you have any further issues (i.e. re-open this one if it remains unsolved, or open a new one if you spot something else). Thanks for your bug report!

**Comment by thecookiemomma** [comment]
Looks like the alt click works, as does putting the correct folder in the correct setting.  Thank you for the prompt fix!  This will help a lot!

**Comment by oldjove** [comment]
Thanks @nybbles ! Seems to work like a treat now.
