### ISSUE TITLE
Mobile compatibility

### ISSUE THREAD

**Issue by dummifiedme** [nybbles/obsidian-pocket#33]
It would really be useful if this could be mobile compatible. Currently, this plugin isn’t available for ObsidianMobile.

**Comment by nybbles** [comment]
- [ ] Use correct API keys for mobile platforms
- [ ] Figure out how cross-device sync should work, since IndexedDB solution does not use Obsidian Sync
- [ ] Remove and replace incompatible modules
  - [ ] qs
  - [ ] process.platform --> `Obsidian.platform`, but still need to wait on the ability to distinguish Linux vs Windows vs Mac OS
  - [ ] uuid --> use something like [this](https://github.com/valentine195/obsidian-leaflet-plugin/blob/01fbecdb99a0372dbae2786039db82922ea5d4d8/src/utils/utils.ts#L55)

**Comment by nybbles** [comment]
Working on this in #41

**Comment by nybbles** [comment]
everything looks good so far.. just need to test my changes more extensively

**Comment by nybbles** [comment]
Closed by #41
