### ISSUE TITLE
Import pocket highlights

### ISSUE THREAD

**Issue by oldjove** [nybbles/obsidian-pocket#34]
Another potentially sweet feature would be to have the ability to import Pocket highlights when creating the relevant Pocket note. Possibly something similar to the new [Readwise plugin](https://github.com/readwiseio/obsidian-readwise).

**Comment by nybbles** [comment]
Thanks for the suggestion, @oldjove, and for the pointer to the Readwise plugin's solution, which looks pretty reasonable. I wanted to let you know that I am aware of it, but that it might take quite a while to get to it, because:

1. I'm working on this plugin on my spare time, which means a small amount of bandwidth every week to make progress on a backlog.
2. I'm prioritizing Pocket usecases in increasing order of complexity, which is (in my mind), link-saving/opening, link filtering/search and then lastly something like highlighting content within links.

That said, pull requests are very welcome (please reach out before writing code, to discuss how to build it) and once I get through the more basic (also probably more widely-used) Pocket usecases, I'd be happy to tackle this.

**Comment by oldjove** [comment]
No worries @nybbles ! I appreciate that this might not be your main project, and I just mention these ideas in a helpful spirit. Unfortunately, I'm not a coder myself, so can't help you on that front. Happy developing!

**Comment by nybbles** [comment]
Just wanted to provide an update here. Pocket does not actually have a publicly-available Highlights API, and has no plans to release one: https://twitter.com/pocketsupport/status/1490796852194811910. I find that pretty disappointing TBH, as I was seriously considering getting started on planning out this functionality.

If you want to see that support, please consider reaching out to Pocket (e.g. tweeting at them, perhaps some other means) and ask that they provide a publicly-available Highlights API, whitelist this plugin or fork it and build it themselves.

I'm closing this one, since there's nothing further I can do here.

**Comment by nybbles** [comment]
Just found this: https://discord.com/channels/686053708261228577/707816848615407697/937306014431191070.

You can get Pocket highlights into Obsidian via Readwise and their officially-supported Obsidian plugin. This does of course mean that you need to pay for Readwise, in addition to Pocket. Just highlighting it as an option for anyone interested.
