### ISSUE TITLE
Shorten the name of the plugin

### ISSUE THREAD

**Issue by rezgi** [nybbles/obsidian-pocket#49]
Bit of a silly request, but what would you think if the plugin's name was shorter ? Right now the plugin is called "Pocket Reading List Integration" which is long and takes 2 lines on the plugin list in Obsidian's settings. Maybe "Pocket Integration" would be ok.

I guess you indicated "reading list" since Pocket is a generic name. Anyway it's up to discussion.

**Comment by chrisgrieser** [comment]
Since there is no other plugin with "pocket" in its name, the generic name won't cause this plugin not to be found. I#d therefore vote for "Pocket Integration"

<img width="236" alt="Screenshot 2021-09-11 20 08 32" src="https://user-images.githubusercontent.com/73286100/132957221-0c90b00b-c9d6-4515-b8d9-d2d1ae116cd3.png">

**Comment by nybbles** [comment]
makes sense
